/**
 * Wari teller API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models';

export interface Customer {
    firstName?: string;

    lastName?: string;

    phoneNumber?: string;

    address?: string;

    identityCountry?: string;

    identityType?: string;

    identityNumber?: string;

    identityExpirationDate?: Date;

    identityEmissionDate?: Date;

    wariSecure?: string;

    accountNumber?: string;

    accountType?: string;

    accountProvider?: string;

    cardType?: string;

    voucher?: string;

    voucherPhone?: string;

    voucherProvider?: string;

    wallet?: string;

    walletProvider?: string;

}
