/**
 * Wari teller API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models';

export interface MerchantForm {
    merchantCode?: string;

    merchantCurrency?: string;

    merchantName?: string;

    merchantCategory?: string;

    merchantAddress?: string;

    merchantType?: string;

    merchantCountry?: { [key: string]: string; };

    formField?: { [key: string]: Array<any>; };

}
