/**
 * Wari teller API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models';

export interface Report {
    date?: string;

    transactionNumber?: string;

    transactionType?: string;

    tellerOffice?: string;

    callCenter?: string;

    supervisor?: string;

    principal?: string;

    provision?: string;

    commissionBank?: string;

    commissionWari?: string;

    commissionDistributor?: string;

    tvaTobCollected?: string;

    tvaSupported?: string;

    tobSupported?: string;

    taxeOperation?: string;

    taxeFixe?: string;

    commissionASD?: string;

    tvaASD?: string;

    tobASD?: string;

}
