/**
 * Wari teller API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models';

export interface TransactionReceipt {
    transactionId?: number;

    date?: string;

    teller?: string;

    printingMode?: string;

    operateur?: string;

    type?: string;

    tellerOffice?: string;

    agency?: string;

    distributor?: string;

    bank?: string;

    senderCountry?: string;

    sender?: models.Customer;

    receiverCountry?: string;

    receiver?: models.Customer;

    transactionSendCode?: string;

    labelPromo?: string;

    clause?: string;

    logoUrl?: string;

    eventMessage?: string;

    reportFooter?: string;

    currency?: string;

    phone?: string;

    address?: string;

    fax?: string;

    principal?: number;

    fees?: number;

    taxes?: number;

    feesWithTaxe?: number;

    timbre?: number;

    total?: number;

    principalConvert?: number;

    labelPrincipalConvert?: string;

    showHorsTaxe?: string;

    mtricule?: string;

    merchant?: string;

    merchantId?: number;

    merchantReference?: string;

    billReference?: string;

    billClient?: string;

    paymentMean?: string;

}
